on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: contrainer.azurecr.io
        username: ${{ secrets.acr_contrainer_username }}
        password: ${{ secrets.acr_contrainer_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/app" -f  "app/Dockerfile" -t contrainer.azurecr.io/louakscluster:${{ github.sha }} --label dockerfile-path=app/Dockerfile
        docker push contrainer.azurecr.io/louakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_louakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep louakscluster8ba4 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace louakscluster8ba4`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: louakscluster8ba4
        container-registry-url: contrainer.azurecr.io
        container-registry-username: ${{ secrets.acr_contrainer_username }}
        container-registry-password: ${{ secrets.acr_contrainer_password }}
        secret-name: louaksclustedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: louakscluster8ba4
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          contrainer.azurecr.io/louakscluster:${{ github.sha }}
        imagepullsecrets: |
          louaksclustedockerauth
